### ISSUE TITLE
你好，按README的Run one shard操作，报错如下请问是什么原因呢？Thanks（已修改dag server真实ip地址）

### ISSUE THREAD

**Issue by fzhiy** [shuoyuan/ChainsFL-implementation#1]
(fl) E:\Labs\FL\ChainsFL-implementation\dagMainChain>python clientRun.py --epochs 1 --frac 0.1 --gpu -1 --model cnn --num_channels 1
D:\Users\fzhiy\anaconda3\envs\fl\lib\site-packages\torchvision\datasets\mnist.py:48: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
The para of iid is False
********************************
CNNMnist(
  (conv1): Conv2d(1, 10, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(10, 20, kernel_size=(5, 5), stride=(1, 1))
  (conv2_drop): Dropout2d(p=0.5, inplace=False)
  (fc1): Linear(in_features=320, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=10, bias=True)
)
********************************
Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Users\fzhiy\anaconda3\envs\fl\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Users\fzhiy\anaconda3\envs\fl\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Users\fzhiy\anaconda3\envs\fl\lib\subprocess.py", line 1083, in _readerthread
    buffer.append(fh.read())
  File "D:\Users\fzhiy\anaconda3\envs\fl\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 4: invalid continuation byte

Traceback (most recent call last):
  File "clientRun.py", line 466, in <module>
    main('xx.xx.xx.xx')
  File "clientRun.py", line 174, in main
    dictUserGetStatus, dictUsersttCodeGet = usefulTools.ipfsGetFile(dict_userf_fileHash, dict_users_file)
  File "../commonComponent\usefulTools.py", line 22, in ipfsGetFile
    outs, errs = ipfsGet.communicate(timeout=10)
  File "D:\Users\fzhiy\anaconda3\envs\fl\lib\subprocess.py", line 863, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "D:\Users\fzhiy\anaconda3\envs\fl\lib\subprocess.py", line 1135, in _communicate
    stderr = stderr[0]
IndexError: list index out of range

**Comment by shuoyuan** [comment]
你好，从目前的日志上来看，主要问题出现在`outs, errs = ipfsGet.communicate(timeout=10)`，所以请确认环境是否搭建完整，并启动IPFS。

**Comment by fzhiy** [comment]
> 你好，从目前的日志上来看，主要问题出现在`outs, errs = ipfsGet.communicate(timeout=10)`，所以请确认环境是否搭建完整，并启动IPFS。

好的，谢谢！
